# Generated by Django 5.0.6 on 2024-06-19 18:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin_rate', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('ethereum_rate', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('usdt_rate', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin_address', models.CharField(max_length=150)),
                ('ethereum_address', models.CharField(max_length=150)),
                ('tether_USDT', models.CharField(max_length=150)),
                ('usdt_ERC20_address', models.CharField(max_length=150)),
                ('bnb_address', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteVisitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('firstname', models.CharField(blank=True, max_length=30)),
                ('lastname', models.CharField(blank=True, max_length=30)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_on_card', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoBalances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin_balance', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('ethereum_balance', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('usdt_balance', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder', models.CharField(blank=True, max_length=100, null=True)),
                ('card_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField()),
                ('cvv', models.IntegerField(blank=True, null=True)),
                ('available_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('card_status', models.CharField(choices=[('Not activated', 'Not activated'), ('Activated', 'Activated'), ('Blocked', 'Blocked')], default='Not activated', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('network', models.CharField(blank=True, max_length=100, null=True)),
                ('proof', models.ImageField(blank=True, null=True, upload_to='payments/')),
                ('status', models.CharField(choices=[('No deposit', 'No Deposit'), ('Failed', 'Failed'), ('Under review', 'Under review'), ('Confirmed', 'Confirmed')], default='', max_length=50)),
                ('status_message', models.TextField(blank=True, max_length=5000, null=True)),
                ('requestID', models.CharField(blank=True, default='', max_length=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IDME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('id_front', models.ImageField(blank=True, null=True, upload_to='id_cards/')),
                ('id_back', models.ImageField(blank=True, null=True, upload_to='id_cards/')),
                ('phone', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('micro', 'Micro'), ('standard', 'Standard'), ('premium', 'Premium'), ('elite', 'Elite'), ('premium-yields', 'Premium Yields'), ('Signatory', 'Signatory')], default='micro', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('duration', models.CharField(max_length=100)),
                ('waiver', models.BooleanField(default=False)),
                ('debit_account', models.CharField(default='', max_length=100)),
                ('reference', models.CharField(default='', max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('rejected', 'Rejected'), ('In progress', 'In progress')], default='awaiting slot entry', max_length=100)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='is_verified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('verification_code', models.IntegerField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MinimumDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome!!', max_length=100)),
                ('message', models.TextField(default='Welcome')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin_address', models.CharField(blank=True, max_length=255, null=True)),
                ('ethereum_address', models.CharField(blank=True, max_length=255, null=True)),
                ('usdt_TRC20_address', models.CharField(blank=True, max_length=255, null=True)),
                ('usdt_ERC20_address', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_login', models.BooleanField(default=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('deposits', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, default=10.0, max_digits=10)),
                ('profits', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('account_manager', models.CharField(blank=True, default='not assigned', max_length=255)),
                ('withdrawal_limit', models.DecimalField(decimal_places=2, default=7000.0, max_digits=10)),
                ('pin', models.IntegerField(default=0)),
                ('can_withraw', models.BooleanField(default=False)),
                ('trade_status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('No Trade', 'No Trade')], default='No Trade', max_length=30)),
                ('verification_status', models.CharField(choices=[('Under review', 'Under Review'), ('Verified', 'Verified'), ('Failed', 'Failed'), ('Awaiting', 'Awaiting')], default='Awaiting', max_length=50)),
                ('alert_user', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='send_email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(blank=True, max_length=255, null=True)),
                ('Message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(default='no data', max_length=100)),
                ('address', models.CharField(default='no data', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('Under review', 'Under review'), ('Failed', 'Failed'), ('Approved', 'Approved')], default='Checking', max_length=30)),
                ('status_message', models.TextField(blank=True, max_length=5000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('RequestID', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
