# Generated by Django 5.0.6 on 2024-06-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_referrals_referrals_alter_referrals_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='title',
            field=models.CharField(default='Welcome!', max_length=100),
        ),
        migrations.AlterField(
            model_name='referrals',
            name='referral_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
