# Generated by Django 5.0.6 on 2024-08-11 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_currencies_profiles_email_alerts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('network', models.CharField(blank=True, max_length=100, null=True)),
                ('hash', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('No deposit', 'No Deposit'), ('Failed', 'Failed'), ('Under review', 'Under review'), ('Confirmed', 'Confirmed')], default='No deposit', max_length=50)),
                ('status_message', models.TextField(blank=True, max_length=5000, null=True)),
                ('deposit_id', models.CharField(blank=True, default='', max_length=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='user',
        ),
        migrations.DeleteModel(
            name='WebsiteVisitors',
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.DeleteModel(
            name='PaymentDetails',
        ),
    ]
