# Generated by Django 5.0.6 on 2024-08-17 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_deposits_remove_deposit_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceeur',
            name='deposits',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text="this balances update automatically based on the user's current balance. You should not change any field here manually.", max_digits=10),
        ),
        migrations.AlterField(
            model_name='balanceusd',
            name='deposits',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text="this balances update automatically based on the user's current balance. You should not change any field here manually.", max_digits=10),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='code',
            field=models.CharField(default='GBP', help_text='these fields are created and updated automatically, please do not change them.', max_length=3),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, help_text="this balances update automatically based on the user's current balance. You should not change any field here manually.", max_digits=10),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='name',
            field=models.CharField(help_text="this balances update automatically based on the user's current balance. You should not change any field here manually.", max_length=50),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='sign',
            field=models.CharField(help_text="this balances update automatically based on the user's current balance. You should not change any field here manually.", max_length=3),
        ),
        migrations.AlterField(
            model_name='deposits',
            name='status',
            field=models.CharField(choices=[('No deposit', 'No Deposit'), ('Failed', 'Failed'), ('Under review', 'Under review'), ('Confirmed', 'Confirmed')], default='No Deposit', max_length=50),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='email_alerts',
            field=models.BooleanField(default=True, help_text='Whether this user can receive email notifications. the user can turn this on or off in their settings'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='pin',
            field=models.IntegerField(default=0, help_text='This PIN is automatically generated but not shown to the user. Without this PIN, the user will not be able to withdraw.', verbose_name='Withdrawal pin'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='preferred_currency',
            field=models.CharField(blank=True, choices=[('GBP', 'GBP'), ('USD', 'USD'), ('EUR', 'EUR')], default='GBP', help_text="User's preferred currency", max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('id_front', models.ImageField(blank=True, null=True, upload_to='id_cards/')),
                ('id_back', models.ImageField(blank=True, null=True, upload_to='id_cards/')),
                ('phone', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='IDME',
        ),
    ]
