# Generated by Django 5.0.6 on 2024-08-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_verification_face'),
    ]

    operations = [
        migrations.AddField(
            model_name='is_verified',
            name='account_verified',
            field=models.BooleanField(default=False),
        ),
    ]
