# Generated by Django 5.0.6 on 2024-08-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_profiles_requires_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='requires_verification_token',
            field=models.BooleanField(default=True, help_text='Decide whether this user needs a verification token to submit account verification requests. If this is Turned on, this token will be automatically generated for this account but will not be mailed to them. You can decide to ask for certain payment to get this token from you. And if Turned off, the user will not be prompted for a verification token to submit account verification requests.', verbose_name='Verification Token'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='verification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
