# Generated by Django 5.0.6 on 2024-08-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_profiles_requires_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='document_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
