# Generated by Django 5.0.6 on 2024-08-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_verification_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletaddress',
            name='lite_coin_address',
            field=models.CharField(default='', max_length=150, verbose_name='Company Litecoin Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='walletaddress',
            name='osmosis_address',
            field=models.CharField(default='', max_length=150, verbose_name='Company Osmosis Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='walletaddress',
            name='solana_address',
            field=models.CharField(default='', max_length=150, verbose_name='Company Solana Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='walletaddress',
            name='ton_address',
            field=models.CharField(default='', max_length=150, verbose_name='Company TON Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='bitcoin_address',
            field=models.CharField(max_length=150, verbose_name='Company Bitcoin Address'),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='bnb_address',
            field=models.CharField(max_length=150, verbose_name='Company Binance Coin Address'),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='ethereum_address',
            field=models.CharField(max_length=150, verbose_name='Company Ethereum Address'),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='tether_USDT',
            field=models.CharField(max_length=150, verbose_name='Company Tether USDT Address'),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='usdt_ERC20_address',
            field=models.CharField(max_length=150, verbose_name='Company USDT ERC20 Address'),
        ),
    ]
