# Generated by Django 5.0.6 on 2024-09-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_investments_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('Under review', 'Under review'), ('Processing', 'Processing'), ('Failed', 'Failed'), ('Approved', 'Approved'), ('Completed', 'Completed')], default='Checking', max_length=30),
        ),
    ]
