# Generated by Django 5.0.6 on 2024-09-21 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_withdrawalrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('In progress', 'In progress')], default='awaiting slot entry', max_length=100),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='requires_verification_token',
            field=models.BooleanField(default=False, help_text='Decide whether this user needs a verification token to submit account verification requests. If this is Turned on, this token will be automatically generated for this account but will not be mailed to them. You can decide to ask for certain payment to get this token from you. And if Turned off, the user will not be prompted for a verification token to submit account verification requests.', verbose_name='Requires Verification Token'),
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=20)),
                ('activity_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('activity_description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
