# Generated by Django 5.0.6 on 2024-09-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_investments_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='activity_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
