# Generated by Django 5.0.6 on 2024-10-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_activities_activity_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardrequest',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='investments',
            name='plan',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='investments',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('In progress', 'In progress')], default='awaiting slot entry', max_length=100),
        ),
    ]
