# Generated by Django 5.0.6 on 2024-10-08 21:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_cardrequest_status_alter_investments_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='investments',
            name='duration',
            field=models.IntegerField(default=5),
        ),
    ]
