# Generated by Django 5.0.6 on 2024-11-12 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_investments_days_remaining_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LossesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loss_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.investments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradingParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_target', models.DecimalField(decimal_places=2, default=12.0, help_text='Specify the Win rate. for example, for a 5x increase, set it to 6.00 . for a slightly over 10x increase, set it to 11.00 or higher', max_digits=10, verbose_name='Profit Increase Rate')),
                ('investment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='app.investments')),
            ],
        ),
    ]
