# Generated by Django 5.0.6 on 2024-07-17 07:01

from django.db import migrations, models
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiries',
            name='ticket_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiries',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now),
            preserve_default=False,
        ),
    ]
