# Generated by Django 5.0.6 on 2024-08-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_enquiries_ticket_id_enquiries_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingJournals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('display_picture', models.ImageField(upload_to='trading_journals/display_pictures')),
                ('file', models.FileField(upload_to='trading_journals/journals', verbose_name='JOURNAL FILE')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
