# Generated by Django 5.0.6 on 2024-08-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_journalpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingjournals',
            name='author',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
