# Generated by Django 5.0.6 on 2024-08-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_journalpayments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalpayments',
            old_name='payment_method',
            new_name='payment_address',
        ),
        migrations.RemoveField(
            model_name='journalpurchase',
            name='confirm_purchase',
        ),
        migrations.AddField(
            model_name='journalpayments',
            name='payment_network',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalpayments',
            name='payment_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalpurchase',
            name='allowed_downloads',
            field=models.IntegerField(default=0),
        ),
    ]
